### ISSUE TITLE
Configure EPS09 to not show a warning when an expression is passed

### ISSUE THREAD

**Issue by BrunoZell** [SergeyTeplyakov/ErrorProne.NET#151]
Given the following function:

```csharp
bool Foo(in decimal x) => x > 0m;
```

I have some method which is utilizing this function in following fashion:
``` csharp
decimal val = 3m;
bool a = Foo(in val);
bool b = Foo(-val);
```

In the first call, everything is fine. In the second call, however, I either get a `EPS09` warning since I do not pass the value by reference or, in the case I add the `in` keyword, a `CS8156` error since I can't pass an expression by reference.

So what is recommended to do in such a case? Should I clutter in a new local variable `decimal valNegated = -val;` and pass that as a reference to `Foo` or should `EPS09` be configurable to not warn in such a case?

Actually, I peeked at the generated IL code and it seems like the compiler is generating a new local under the hood and is passing it as a `ref` parameter, to there should be no difference in performance I guess.

**Comment by Voidzer0** [comment]
Please correct me, if I'm wrong, but I do not understand why this warning is raised in cases where argument and parameter are of exactly the same type at all.
As far as I know, the compiler will pass the argument as in (read-only reference) if the parameter is declared as "in" param and the argument is suitable to be passed as reference(it's a variable of same type as the param), without explicitely writing it.
What I mean is, that:
`Foo(in val);`
Will be compiled to the exactly same as IL:
`Foo(val);`
In both cases the compiler should pass it as reference, because of the parameter declaration says "in" and argument 'val' is a variable and is of same type as param 'x'.
Writing "in" infront of the argument should not be necessary in such cases.
See last lines 2 lines of the 4th code listing here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier

Cheers

**Comment by CianNoonan** [comment]
I've also run into this issue. It'd be great if we could get some clarity on why this warning is here. Is it just style enforcement or does it make a semantic change? @SergeyTeplyakov

**Comment by BrunoZell** [comment]
Found some [good piece of documentation](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#apply-the-in-modifier-to-readonly-struct-parameters-larger-than-systemintptrsize) about the behavior of the `in` modifier:

> Another feature of `in` parameters is that you may use literal values or constants for the argument to an in parameter. Also, unlike a `ref` or `out` parameter, **you don't need to apply the in modifier at the call site.**

Further on it states:

> The use of in parameters can avoid the potential performance costs of making copies. It doesn't change the semantics of any method call. Therefore, you don't need to specify the in modifier at the call site. **Omitting the in modifier at the call site informs the compiler that it's allowed to make a copy of the argument for the following reasons:**
> - There exists an implicit conversion but not an identity conversion from the argument type to the parameter type.
> - The argument is an expression but doesn't have a known storage variable.
> - An overload exists that differs by the presence or absence of in. In that case, the by value overload is a better match.
